/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'
import { Route as AssessmentsIdTakeRouteImport } from './routes/assessments.$id.take'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as InterviewsIdRouteImport } from './routes/interviews.$id'
import { Route as InterviewsNewRouteImport } from './routes/interviews.new'
import { Route as InterviewsIdConductRouteImport } from './routes/interviews.$id.conduct'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnersIdRouteImport } from './routes/partners.$id'
import { Route as PartnersNewRouteImport } from './routes/partners.new'
import { Route as IndexRouteImport } from './routes/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)

const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/new',
  getParentRoute: () => AssessmentsRoute,
} as any)

const AssessmentsIdTakeRoute = AssessmentsIdTakeRouteImport.update({
  id: '/assessments/$id/take',
  path: '/$id/take',
  getParentRoute: () => AssessmentsRoute,
} as any)

const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)

const InterviewsNewRoute = InterviewsNewRouteImport.update({
  id: '/interviews/new',
  path: '/new',
  getParentRoute: () => InterviewsRoute,
} as any)

const InterviewsIdRoute = InterviewsIdRouteImport.update({
  id: '/interviews/$id',
  path: '/$id',
  getParentRoute: () => InterviewsRoute,
} as any)

const InterviewsIdConductRoute = InterviewsIdConductRouteImport.update({
  id: '/interviews/$id/conduct',
  path: '/$id/conduct',
  getParentRoute: () => InterviewsRoute,
} as any)

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)

const PartnersIdRoute = PartnersIdRouteImport.update({
  id: '/partners/$id',
  path: '/$id',
  getParentRoute: () => PartnersRoute,
} as any)

const PartnersNewRoute = PartnersNewRouteImport.update({
  id: '/partners/new',
  path: '/new',
  getParentRoute: () => PartnersRoute,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/assessments/$id/take': typeof AssessmentsIdTakeRoute
  '/interviews': typeof InterviewsRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/interviews/new': typeof InterviewsNewRoute
  '/interviews/$id/conduct': typeof InterviewsIdConductRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/partners/$id': typeof PartnersIdRoute
  '/partners/new': typeof PartnersNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/assessments/$id/take': typeof AssessmentsIdTakeRoute
  '/interviews': typeof InterviewsRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/interviews/new': typeof InterviewsNewRoute
  '/interviews/$id/conduct': typeof InterviewsIdConductRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/partners/$id': typeof PartnersIdRoute
  '/partners/new': typeof PartnersNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/assessments/$id/take': typeof AssessmentsIdTakeRoute
  '/interviews': typeof InterviewsRoute
  '/interviews/$id': typeof InterviewsIdRoute
  '/interviews/new': typeof InterviewsNewRoute
  '/interviews/$id/conduct': typeof InterviewsIdConductRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/partners/$id': typeof PartnersIdRoute
  '/partners/new': typeof PartnersNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/assessments' | '/assessments/new' | '/assessments/$id/take' | '/interviews' | '/interviews/$id' | '/interviews/new' | '/interviews/$id/conduct' | '/login' | '/partners' | '/partners/$id' | '/partners/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/assessments' | '/assessments/new' | '/interviews' | '/interviews/$id' | '/interviews/new' | '/interviews/$id/conduct' | '/login' | '/partners' | '/partners/$id' | '/partners/new'
  id: '__root__' | '/' | '/about' | '/assessments' | '/assessments/new' | '/interviews' | '/interviews/$id' | '/interviews/new' | '/interviews/$id/conduct' | '/login' | '/partners' | '/partners/$id' | '/partners/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentsRoute: typeof AssessmentsRoute
  AssessmentsNewRoute: typeof AssessmentsNewRoute
  InterviewsRoute: typeof InterviewsRoute
  InterviewsIdRoute: typeof InterviewsIdRoute
  InterviewsNewRoute: typeof InterviewsNewRoute
  InterviewsIdConductRoute: typeof InterviewsIdConductRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PartnersIdRoute: typeof PartnersIdRoute
  PartnersNewRoute: typeof PartnersNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/assessments/$id/take': {
      id: '/assessments/$id/take'
      path: '/$id/take'
      fullPath: '/assessments/$id/take'
      preLoaderRoute: typeof AssessmentsIdTakeRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/$id': {
      id: '/interviews/$id'
      path: '/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof InterviewsIdRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/interviews/new': {
      id: '/interviews/new'
      path: '/new'
      fullPath: '/interviews/new'
      preLoaderRoute: typeof InterviewsNewRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/interviews/$id/conduct': {
      id: '/interviews/$id/conduct'
      path: '/$id/conduct'
      fullPath: '/interviews/$id/conduct'
      preLoaderRoute: typeof InterviewsIdConductRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$id': {
      id: '/partners/$id'
      path: '/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof PartnersIdRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/new': {
      id: '/partners/new'
      path: '/new'
      fullPath: '/partners/new'
      preLoaderRoute: typeof PartnersNewRouteImport
      parentRoute: typeof PartnersRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentsRoute: AssessmentsRoute,
  AssessmentsNewRoute: AssessmentsNewRoute,
  AssessmentsIdTakeRoute: AssessmentsIdTakeRoute,
  InterviewsRoute: InterviewsRoute,
  InterviewsIdRoute: InterviewsIdRoute,
  InterviewsNewRoute: InterviewsNewRoute,
  InterviewsIdConductRoute: InterviewsIdConductRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PartnersIdRoute: PartnersIdRoute,
  PartnersNewRoute: PartnersNewRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router'
import type { createStart } from '@tanstack/react-start'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
