/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersNewRouteImport } from './routes/partners.new'
import { Route as PartnersIdRouteImport } from './routes/partners.$id'
import { Route as InterviewsNewRouteImport } from './routes/interviews.new'
import { Route as InterviewsIdRouteImport } from './routes/interviews.$id'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'
import { Route as InterviewsIdConductRouteImport } from './routes/interviews.$id.conduct'
import { Route as AssessmentsIdTakeRouteImport } from './routes/assessments.$id.take'
import { Route as AssessmentsIdResultsRouteImport } from './routes/assessments.$id.results'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersNewRoute = PartnersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PartnersRoute,
} as any)
const PartnersIdRoute = PartnersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartnersRoute,
} as any)
const InterviewsNewRoute = InterviewsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InterviewsRoute,
} as any)
const InterviewsIdRoute = InterviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InterviewsRoute,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AssessmentsRoute,
} as any)
const InterviewsIdConductRoute = InterviewsIdConductRouteImport.update({
  id: '/conduct',
  path: '/conduct',
  getParentRoute: () => InterviewsIdRoute,
} as any)
const AssessmentsIdTakeRoute = AssessmentsIdTakeRouteImport.update({
  id: '/$id/take',
  path: '/$id/take',
  getParentRoute: () => AssessmentsRoute,
} as any)
const AssessmentsIdResultsRoute = AssessmentsIdResultsRouteImport.update({
  id: '/$id/results',
  path: '/$id/results',
  getParentRoute: () => AssessmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/interviews': typeof InterviewsRouteWithChildren
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/interviews/$id': typeof InterviewsIdRouteWithChildren
  '/interviews/new': typeof InterviewsNewRoute
  '/partners/$id': typeof PartnersIdRoute
  '/partners/new': typeof PartnersNewRoute
  '/assessments/$id/results': typeof AssessmentsIdResultsRoute
  '/assessments/$id/take': typeof AssessmentsIdTakeRoute
  '/interviews/$id/conduct': typeof InterviewsIdConductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/interviews': typeof InterviewsRouteWithChildren
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/interviews/$id': typeof InterviewsIdRouteWithChildren
  '/interviews/new': typeof InterviewsNewRoute
  '/partners/$id': typeof PartnersIdRoute
  '/partners/new': typeof PartnersNewRoute
  '/assessments/$id/results': typeof AssessmentsIdResultsRoute
  '/assessments/$id/take': typeof AssessmentsIdTakeRoute
  '/interviews/$id/conduct': typeof InterviewsIdConductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/interviews': typeof InterviewsRouteWithChildren
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/interviews/$id': typeof InterviewsIdRouteWithChildren
  '/interviews/new': typeof InterviewsNewRoute
  '/partners/$id': typeof PartnersIdRoute
  '/partners/new': typeof PartnersNewRoute
  '/assessments/$id/results': typeof AssessmentsIdResultsRoute
  '/assessments/$id/take': typeof AssessmentsIdTakeRoute
  '/interviews/$id/conduct': typeof InterviewsIdConductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessments'
    | '/interviews'
    | '/login'
    | '/partners'
    | '/profile'
    | '/assessments/new'
    | '/interviews/$id'
    | '/interviews/new'
    | '/partners/$id'
    | '/partners/new'
    | '/assessments/$id/results'
    | '/assessments/$id/take'
    | '/interviews/$id/conduct'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessments'
    | '/interviews'
    | '/login'
    | '/partners'
    | '/profile'
    | '/assessments/new'
    | '/interviews/$id'
    | '/interviews/new'
    | '/partners/$id'
    | '/partners/new'
    | '/assessments/$id/results'
    | '/assessments/$id/take'
    | '/interviews/$id/conduct'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessments'
    | '/interviews'
    | '/login'
    | '/partners'
    | '/profile'
    | '/assessments/new'
    | '/interviews/$id'
    | '/interviews/new'
    | '/partners/$id'
    | '/partners/new'
    | '/assessments/$id/results'
    | '/assessments/$id/take'
    | '/interviews/$id/conduct'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentsRoute: typeof AssessmentsRouteWithChildren
  InterviewsRoute: typeof InterviewsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/new': {
      id: '/partners/new'
      path: '/new'
      fullPath: '/partners/new'
      preLoaderRoute: typeof PartnersNewRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/partners/$id': {
      id: '/partners/$id'
      path: '/$id'
      fullPath: '/partners/$id'
      preLoaderRoute: typeof PartnersIdRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/interviews/new': {
      id: '/interviews/new'
      path: '/new'
      fullPath: '/interviews/new'
      preLoaderRoute: typeof InterviewsNewRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/interviews/$id': {
      id: '/interviews/$id'
      path: '/$id'
      fullPath: '/interviews/$id'
      preLoaderRoute: typeof InterviewsIdRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/interviews/$id/conduct': {
      id: '/interviews/$id/conduct'
      path: '/conduct'
      fullPath: '/interviews/$id/conduct'
      preLoaderRoute: typeof InterviewsIdConductRouteImport
      parentRoute: typeof InterviewsIdRoute
    }
    '/assessments/$id/take': {
      id: '/assessments/$id/take'
      path: '/$id/take'
      fullPath: '/assessments/$id/take'
      preLoaderRoute: typeof AssessmentsIdTakeRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/assessments/$id/results': {
      id: '/assessments/$id/results'
      path: '/$id/results'
      fullPath: '/assessments/$id/results'
      preLoaderRoute: typeof AssessmentsIdResultsRouteImport
      parentRoute: typeof AssessmentsRoute
    }
  }
}

interface AssessmentsRouteChildren {
  AssessmentsNewRoute: typeof AssessmentsNewRoute
  AssessmentsIdResultsRoute: typeof AssessmentsIdResultsRoute
  AssessmentsIdTakeRoute: typeof AssessmentsIdTakeRoute
}

const AssessmentsRouteChildren: AssessmentsRouteChildren = {
  AssessmentsNewRoute: AssessmentsNewRoute,
  AssessmentsIdResultsRoute: AssessmentsIdResultsRoute,
  AssessmentsIdTakeRoute: AssessmentsIdTakeRoute,
}

const AssessmentsRouteWithChildren = AssessmentsRoute._addFileChildren(
  AssessmentsRouteChildren,
)

interface InterviewsIdRouteChildren {
  InterviewsIdConductRoute: typeof InterviewsIdConductRoute
}

const InterviewsIdRouteChildren: InterviewsIdRouteChildren = {
  InterviewsIdConductRoute: InterviewsIdConductRoute,
}

const InterviewsIdRouteWithChildren = InterviewsIdRoute._addFileChildren(
  InterviewsIdRouteChildren,
)

interface InterviewsRouteChildren {
  InterviewsIdRoute: typeof InterviewsIdRouteWithChildren
  InterviewsNewRoute: typeof InterviewsNewRoute
}

const InterviewsRouteChildren: InterviewsRouteChildren = {
  InterviewsIdRoute: InterviewsIdRouteWithChildren,
  InterviewsNewRoute: InterviewsNewRoute,
}

const InterviewsRouteWithChildren = InterviewsRoute._addFileChildren(
  InterviewsRouteChildren,
)

interface PartnersRouteChildren {
  PartnersIdRoute: typeof PartnersIdRoute
  PartnersNewRoute: typeof PartnersNewRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersIdRoute: PartnersIdRoute,
  PartnersNewRoute: PartnersNewRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentsRoute: AssessmentsRouteWithChildren,
  InterviewsRoute: InterviewsRouteWithChildren,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRouteWithChildren,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
